// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yphbtrhnrlkovgqejdcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwaGJ0cmhucmxrb3ZncWVqZGNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTY4NTQsImV4cCI6MjA2OTg5Mjg1NH0.Tojcj72ho3jyh-JEkjtMb208w6m-PzNHlbSEB7RPnFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});